### ISSUE TITLE
Base Feature Enhancement

### ISSUE THREAD

**Issue by vinaynaman** [katonic-dev/explainit#10]
- [x]  Statistical Metrics Rows
- [x] Distribution & Drift Graphs
- [x] Target Drift Main Graph
- [x] Target Drift based on Individual Feature
- [x] Data Summary
- [x] Feature Summary
- [x] Correlation Graphs
- [x] Components Integration

**Comment by shailesh-katonic** [comment]
- [x] Updated `Contribution Guide`
- [x] Added `CODE_OF_CONDUCT`
- [x] Updated `Roadmap`

**Comment by shailesh-katonic** [comment]
- [x] Added `Statistical-test` Tests
